### PR TITLE
Added PHP examples to the appendix

### PR DESCRIPTION
**Pull request by ptersilie**
This PR adds a few PHP error recovery examples to the appendix. It's only 3, since my creativity let me down after that. If you have ideas for more I'm happy to add them.

### CODE REVIEW

**Comment by ltratt** [comment]
I think you forgot to add the `.php` files?

**Comment by ptersilie** [comment]
Sorry, fixed!

**Comment by ltratt** [comment]
If you squash, I can merge.

**Comment by ptersilie** [comment]
No need for more examples?

**Comment by ltratt** [comment]
We can always add more as we think of them.

**Comment by ptersilie** [comment]
Squashed!

**Pull request merged**
